@startuml Pantry Manager Classes

header PantrySync.pro
right footer Let that sync in...
title Database Structure

    entity User {
        *id : int <<PK>>
        *name : string
        *email : string <<Unique>>
        *password : string
    }

    entity Group {
        *id : int <<PK>>
        *name : string
    }

    entity GroupMember {
        *id : int <<PK>>
        *group_id : int <<FK>>
        *user_id : int <<FK>>
        ' Role can be expanded to something dynamic rather than an enum
        *role : enum
    }

    entity Item {
        *id: int <<PK>>
        *group_id : <<FK>>
        *name : string
        *description: string
        ' Category could be an enum
        *category : string
    }

    entity Pantry {
        *id: int <<PK>>
        *item_id : <<FK>>
        *quantity : int
        *minimum_threshold : int
        *auto_add_to_shopping_list : bool
    }

    entity ShoppingList {
        *id: int <<PK>>
        *item_id : <<FK>>
        *quantity : int
    }

    entity Recipes {
        *id : int <<PK>>
        *user_id : int <<FK>>
        *name : string
        /' Including ingredients here for the purpose of identifying possible recipes for given ingredients would
           require a more advanced structure.
        '/
        *instructions : text
    }
    
    entity ActionLog {
        ' Is this an audit log?
        *id : int <<PK>>
        *group_id : int <<FK>>
        *message : string
        *timestamp : datetime
    }

    entity Session {
        *id : int <<PK>>
        *user_id : int <<FK>>
        *token : string
        *create_date : datetime
        *last_use_date : datetime
    }

    User  ||--o{ GroupMember
    User  ||--o{ Recipes
    User  ||--o{ Session
    Group ||--o{ ActionLog
    Group ||--o{ GroupMember
    Group ||--o{ Item
    Item  ||--o{ Pantry
    Item  ||--o{ ShoppingList

@enduml
